source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

gem 'rails', '~> 6.1.5'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 5.0'
gem 'devise'
gem 'devise_token_auth'
gem 'omniauth'
gem 'carrierwave', '~> 2.0'
gem 'mini_magick'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rack-cors'
gem 'will_paginate'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'spring-commands-rspec'
  gem 'database_cleaner'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
